#!/bin/sh

if test -z "$1"; then
   echo "usage: $0 <version>"
   exit 1
fi

dir="cbrowser-$1"

mkdir $dir
cp cbrowser widget.tcl hierarchy.tcl calltree.tcl builder.tcl ftcllib.tcl README $dir
(cd $dir; echo auto_mkindex $PWD widget.tcl hierarchy.tcl calltree.tcl builder.tcl ftcllib.tcl | tclsh)

tar -cf $dir.tar $dir
gzip $dir.tar

